"use client"
import React, { useState, useEffect } from "react";
import Link from "next/link";
import Head from "next/head";
import { useRouter } from "next/navigation";
import styles from "@/app/LandingPage.module.css";

export default function HomePage() {
    const router = useRouter();

    function handleLogin() {
        router.push('/login');
    }

    function handleSignUp() {
        router.push('/signup');
    }
    return (
        <div className={styles.HomePage}>
            <Head>
                <title>Group Buying Web App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/buy.png" />
            </Head>

            <div className={styles.headerBackground}>

            </div>

            <div className={styles.page}>
                <section className={styles.heading} >
                    <div className={styles.titleAndLogo}>
                        <div className={styles.logo}>
                            <img src="/gBuy_icon.png" className="text-blue-950" />
                        </div>

                        <p className="text-xl ">Discount Hub</p>
                    </div>

                    <div className={styles.appAccess}>
                        <span className={styles.button} onClick={handleSignUp}>Create Account</span>
                        <span className={styles.button} onClick={handleLogin}>Login</span>
                    </div>
                </section>

                <section className={styles.item}>
                    <div className={styles.subItem}>
                        <h1>Join the Power of Group Buying</h1>
                        <p>Discover the best deals on your favorite products by shopping with others.</p>
                    </div>

                    <img src="./product2.jpeg" alt="" />
                </section>

                <section className={styles.item1}>
                    <div className={styles.subItem}>
                        <h1 >Maximum savings</h1>
                        <p>Become part of a group to buy products at a lower price. with Discount Hub, you can save up to 50% off retail prices.</p>
                    </div>
                    <img src="/product3.jpeg" alt="" />
                </section>


                <section className={styles.item}>
                    <div className={styles.subItem}>
                        <h1>Convenient shopping</h1>
                        <p>With the Discount Hub, you no loger need to waste time searching for the best deals. Just browse the site, join a group, and make your purchase</p>
                    </div>

                    <img src="/product4.jpeg" alt="" />
                </section>

                <section >
                    <h1>Big selection</h1>
                    <p>Discount Hub offers a wide selection of products in various categories, including electronics, beauty, fashion, and more. You can find everything you need in one place.</p>
                    <p>"The group buying feature is a game-changer. It's so much fun to shop with others and save money together."</p>
                </section>
            </div>
            <footer className={styles.footer}>


            </footer>

        </div>



    )
}

