"use client"
import React from "react";
import Link from "next/link";
import Head from "next/head";
import { useRouter } from "next/navigation";
import styles from "@/app/LandingPage.module.css";
import { HiUserGroup } from "react-icons/hi";

export default function HomePage() {
    const router = useRouter();

    function handleLogin() {
        router.push('/login');
    }

    function handleSignUp() {
        router.push('/signup');
    }
    return (
        <div className="min-h-screen  w-screen mx-auto bg-center relative  bg-[url('/Image.png')] bg-cover px-28 py-5">
            <Head>
                <title>Group Buying Web App</title>

                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/buy.png" />
            </Head>

            <div>
                <nav className="flex items-center">
                    <div>
                        <span className="w-40 cursor-pointer text-2xl font-semibold"><HiUserGroup className="inline-block mr-2 text-6xl text-blue-600 group-hover:text-white "/>groupbuy</span>
                    </div>
                    
                <ul className="flex-1 text-center">
                    <li className="list-none inline-block px-5"><a href="#" className="no-underline px-2">Home</a></li>
                    <li className="list-none inline-block px-5"><a href="#" className="no-underline px-2">About</a></li>
                    <li className="list-none inline-block px-5"><a href="#" className="no-underline px-2">Features</a></li>
                    <li className="list-none inline-block px-5"><a href="#" className="no-underline px-2">Contact</a></li>
                </ul>
                <img src="/cart.png" className="w-8 cursor-pointer" alt="cart" />
                </nav>
            </div>

            <div className="mt-48 max-w-xl">
                <h1 className="text-6xl font-semibold leading-normal mb-5">GroupBuy</h1>

                <p className="text-lg">Join our vibrant community of like-minded individuals! Together, we amplify our resources, <span className="">incredible discounts</span> unlock , and pave the way for shared success. 

                <div className="mt-5 font-medium text-blue-600">Embrace the power of unity and start saving while achieving more.</div> 
                </p>
            </div>

            <div className="mt-10 text-4xl">Join us today and let's thrive together!</div>
            <div className="mt-10">
                <a onClick={handleLogin} className="bg-blue-600 rounded-3xl text-white py-3 px-8 font-medium inline-block mr-6 hover:bg-transparent hover:border-blue-600 hover:text-white duration-300 hover:border border border-transparent cursor-pointer">Login</a>
                <a onClick={handleSignUp} className="bg-blue-600 rounded-3xl text-white py-3 px-8 font-medium inline-block ,r-4 hover:bg-transparent hover:border-blue-600 hover:text-white duration-300 hover:border border border-transparent cursor-pointer">Signup</a>
            </div>

            {/* <img
                className="w-full xl:w-1/2 xl:absolute top-5 bottom-0"
                src="/grocery_image.png" 
                alt="homepage image" 
            /> */}
        </div>
    )
}

